# Generated by Django 2.1.9 on 2019-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(default='Computer Science & Engineering', max_length=50),
        ),
    ]
