# Generated by Django 2.1.9 on 2019-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191017_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barcode',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
