# Generated by Django 2.1.9 on 2019-10-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_per_day', models.PositiveIntegerField(default=1)),
                ('fine_threshold', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
