# Generated by Django 2.1.9 on 2019-10-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('attachments', models.FileField(blank=True, upload_to='announcements')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
