# Generated by Django 2.1.9 on 2019-10-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ISBN', models.CharField(max_length=30)),
                ('book_number', models.PositiveIntegerField(default=1)),
                ('book_title', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_category', models.CharField(max_length=30)),
                ('book_publisher', models.CharField(max_length=30)),
                ('book_language', models.CharField(max_length=30)),
                ('book_type', models.CharField(choices=[('E-Book Only', 'E-Book Only'), ('Hard Cover Only', 'Hard Cover Only'), ('Both Hard Cover and E-Book', 'Both Hard Cover and E-Book')], default='E-Book Only', max_length=26)),
                ('ebook_attachments', models.FileField(blank=True, upload_to='catalog/ebooks')),
                ('book_price', models.PositiveIntegerField(default=1)),
                ('book_quantity', models.PositiveIntegerField(default=1)),
                ('book_shelf', models.CharField(max_length=10)),
                ('book_date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
