# Generated by Django 2.1.9 on 2019-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_ISBN',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_language',
            field=models.CharField(default='ENG-US', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_shelf',
            field=models.CharField(default='1A', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('E-Book Only', 'E-Book Only'), ('Hard Cover Only', 'Hard Cover Only'), ('Both Hard Cover and E-Book', 'Both Hard Cover and E-Book')], default='Hard Cover Only', max_length=26),
        ),
    ]
