# Generated by Django 2.1.9 on 2019-11-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author2',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='book_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_publisher',
            field=models.CharField(default='Information not available', max_length=30),
        ),
    ]
