# Generated by Django 2.1.9 on 2019-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191107_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
