# Generated by Django 2.1.9 on 2019-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191107_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(blank=True, default='No Info', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author2',
            field=models.CharField(blank=True, default='No Info', max_length=30, null=True),
        ),
    ]
